"""
SQLAlchemy models.
Per HANDOFF.md's "DB tables (core)" section - only the `users` table is
implemented here since auth is the current scope. Whoever builds
assignments.py / submissions.py / flags.py adds Assignment, Question,
Submission, SimilarityPair, AiSimilarity, PerplexityScore, FlagSummary
to THIS file (single source of truth for schema) - do not create a second
models file.

Design note on `id`:
Supabase Auth issues its own UUID per user (in its internal `auth.users`
table, which we don't manage). Our `users` table is a PROFILE table keyed
by that same UUID - it stores the one thing Supabase Auth doesn't: role.
This is the standard Supabase pattern (auth.users for credentials,
public.users/profiles for app-specific fields).
"""

from sqlalchemy import Column, String
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class User(Base):
    __tablename__ = "users"

    # This id is NOT auto-generated by us - it's copied from Supabase Auth's
    # user.id (a UUID string) at signup time, so the two systems always agree
    # on who's who.
    id = Column(String, primary_key=True)
    name = Column(String, nullable=False)
    email = Column(String, unique=True, nullable=False)
    role = Column(String, nullable=False)  # "student" | "ta" | "professor"
